name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=<your_project_key>
            -Dsonar.organization=<your_organization>
            -Dsonar.sarif.filepath=results.sarif # Ensure SARIF file is generated
            -Dsonar.verbose=true

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
